name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: [self-hosted, docker]
    env:
      COMPOSE_PROJECT_NAME: ci-scan-ruby-${{ github.run_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start app container
        run: docker compose up -d app

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: docker compose exec app bin/brakeman --no-pager

      - name: Scan for known security vulnerabilities in gems used
        run: docker compose exec app bin/bundler-audit

      - name: Tear down
        if: always()
        run: docker compose down

  lint:
    runs-on: [self-hosted, docker]
    env:
      COMPOSE_PROJECT_NAME: ci-lint-${{ github.run_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start app container
        run: docker compose up -d app

      - name: Lint code for consistent style
        run: docker compose exec app bin/rubocop -f github

      - name: Tear down
        if: always()
        run: docker compose down

  test:
    runs-on: [self-hosted, docker]
    env:
      COMPOSE_PROJECT_NAME: ci-test-${{ github.run_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start app container
        run: docker compose up -d app

      - name: Set up test database
        run: docker compose exec app bin/rails db:test:prepare

      - name: Run RSpec
        run: docker compose exec app bundle exec rspec --format documentation

      - name: Tear down
        if: always()
        run: docker compose down
